ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'CAPTCHA_REQUIRED';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'RATE_LIMITED';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'UNKNOWN_REQUIRED_FIELD';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'LOGIN_REQUIRED';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'AUTH_REQUIRED';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'CLOUDFLARE_CHALLENGE';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'FORM_NOT_FOUND';
ALTER TYPE "ApplicationPackageStatus" ADD VALUE IF NOT EXISTS 'SUBMISSION_UNCONFIRMED';
